language: ruby
cache: bundler
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - jruby-head
env:
  - ACTIVE_MODEL_VERSION='~> 4.2'
  - ACTIVE_MODEL_VERSION='~> 5.2'
  - ACTIVE_MODEL_VERSION='~> 6.0'
jobs:
  exclude:
    - rvm: 2.7.0
      env: ACTIVE_MODEL_VERSION='~> 4.2'
gemfile: Gemfile
notifications:
  recipients:
    - jeremy@tregunna.ca
