version: "3"

services:
  ruby_2_5:
    image: ruby:2.5.8
    tmpfs:
      - /tmp
    volumes:
      - .:/app:cached
      - bundle_ruby_2_5:/bundle
      - ./Gemfile.lock.ruby_2_5:/app/Gemfile.lock
    environment:
      BUNDLE_PATH: /bundle
    working_dir: /app

  ruby_2_6:
    image: ruby:2.6.6
    tmpfs:
      - /tmp
    volumes:
      - .:/app:cached
      - bundle_ruby_2_6:/bundle
      - ./Gemfile.lock.ruby_2_6:/app/Gemfile.lock
    environment:
      BUNDLE_PATH: /bundle
    working_dir: /app

  ruby_2_7:
    image: ruby:2.7.1
    tmpfs:
      - /tmp
    volumes:
      - .:/app:cached
      - bundle_ruby_2_7:/bundle
      - ./Gemfile.lock.ruby_2_7:/app/Gemfile.lock
    environment:
      BUNDLE_PATH: /bundle
    working_dir: /app

  ruby_3_0:
    image: ruby:3.0.0
    tmpfs:
      - /tmp
    volumes:
      - .:/app:cached
      - bundle_ruby_3_0:/bundle
      - ./Gemfile.lock.ruby_3_0:/app/Gemfile.lock
    environment:
      BUNDLE_PATH: /bundle
    working_dir: /app

  jruby_9_2:
    image: jruby:9.2.11.1
    tmpfs:
      - /tmp
    volumes:
      - .:/app:cached
      - bundle_jruby_9_2:/bundle
      - ./Gemfile.lock.jruby:/app/Gemfile.lock
    environment:
      BUNDLE_PATH: /bundle
    working_dir: /app

volumes:
  bundle_jruby_9_2:
  bundle_ruby_2_5:
  bundle_ruby_2_6:
  bundle_ruby_2_7:
  bundle_ruby_3_0: